import { useEffect, useState } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import {
  Menu,
  X,
  ShieldCheck,
  GitBranch,
  Activity,
  FileText,
  Database,
  ChevronDown,
  ArrowRight,
} from "lucide-react";

export const Route = createFileRoute("/")({ component: HomePage });

const ACCENT = "#22e6c8";
const BG = "#0b0f14";
const PANEL_BG = "rgba(255,255,255,0.03)";
const BORDER = "rgba(255,255,255,0.08)";
const MUTED = "#8798a8";

const NAV_LINKS = [
  { label: "Features", id: "features" },
  { label: "How It Works", id: "how-it-works" },
  { label: "Technology", id: "technology" },
  { label: "FAQ", id: "faq" },
];

const FEATURES = [
  {
    icon: GitBranch,
    title: "Multi-Hop Wallet Tracing",
    desc: "Trace transaction relationships across configurable hop levels, following funds as they move between wallets.",
  },
  {
    icon: Database,
    title: "Real Blockchain Transaction Analysis",
    desc: "Investigations run on actual on-chain transaction data — not mock or simulated data.",
  },
  {
    icon: ShieldCheck,
    title: "Risk Assessment",
    desc: "Wallet behavior is analyzed by the RiskEngine to produce a composite risk score and contributing signals.",
  },
  {
    icon: Activity,
    title: "Investigation Timeline",
    desc: "Chronological transaction evidence laid out for investigators to review hop-by-hop.",
  },
  {
    icon: FileText,
    title: "Evidence & Reports",
    desc: "Generate investigation reports containing case details and traced transaction evidence.",
  },
  {
    icon: ShieldCheck,
    title: "Freeze Request Workflow",
    desc: "Create, review, and track freeze requests tied to suspicious cases through an auditable workflow.",
  },
];

const STEPS = [
  {
    n: "01",
    title: "Create Case",
    desc: "Investigator creates a case with complaint and wallet information.",
  },
  {
    n: "02",
    title: "Trace Wallet",
    desc: "CryptoTrace retrieves and analyzes real blockchain transactions across selected hop levels.",
  },
  {
    n: "03",
    title: "Assess Risk",
    desc: "Transaction behavior is analyzed and a risk score is generated by the RiskEngine.",
  },
  {
    n: "04",
    title: "Take Action",
    desc: "Investigator reviews evidence, generates reports, and initiates the freeze-request workflow.",
  },
];

const BUILD_BLOCKS = [
  {
    icon: ShieldCheck,
    title: "Investigator Workspace",
    desc: "A responsive case dashboard where investigators create cases, review wallets, and track progress in real time.",
  },
  {
    icon: GitBranch,
    title: "Tracing Engine",
    desc: "Pulls live Ethereum transaction data and walks the fund flow hop-by-hop, streaming results as they're found.",
  },
  {
    icon: Activity,
    title: "Risk Engine",
    desc: "Scores traced wallet behavior against fraud signals — velocity, fan-out, hop depth — into a single composite score.",
  },
  {
    icon: Database,
    title: "Case Store",
    desc: "Every case, trace, and status change is persisted so investigations can be reopened and audited later.",
  },
  {
    icon: FileText,
    title: "Evidence & Reports",
    desc: "Turns traced transactions and risk signals into a structured, exportable investigation report.",
  },
  {
    icon: ShieldCheck,
    title: "Freeze Workflow",
    desc: "Routes freeze recommendations through review stages, keeping a full audit trail of every decision.",
  },
];

// Trimmed: only the 2 most important questions per category (was 35 total, now 12)
const FAQS: { category: string; items: { q: string; a: string }[] }[] = [
  {
    category: "General",
    items: [
      { q: "What is CryptoTrace?", a: "CryptoTrace is a digital asset investigation workspace that helps investigators trace suspicious cryptocurrency wallets, analyze transaction behavior, assess risk, and build evidence-backed case files." },
      { q: "How does CryptoTrace help investigators?", a: "It automates multi-hop wallet tracing on real blockchain data, surfaces a computed risk score, organizes evidence chronologically, and helps generate reports and freeze requests." },
    ],
  },
  {
    category: "Blockchain / Tracing",
    items: [
      { q: "Does CryptoTrace use real blockchain data?", a: "Yes. Wallet analysis and traces are built from actual on-chain transaction data, not mock datasets." },
      { q: "Can an investigator choose the number of tracing hops?", a: "Yes, the max-hops setting is configurable per trace, from 1 up to 10 hops." },
    ],
  },
  {
    category: "Risk Analysis",
    items: [
      { q: "How is the wallet risk score calculated?", a: "The RiskEngine evaluates the traced transaction set — factors like fan-in/out, transaction velocity, hop depth, error rate, and value concentration — to compute a composite score out of 100." },
      { q: "Does CryptoTrace automatically decide that someone is guilty?", a: "No. CryptoTrace only surfaces risk signals and evidence. All investigative and legal conclusions are made by the human investigator." },
    ],
  },
  {
    category: "Case Management",
    items: [
      { q: "What information is stored in a case?", a: "Complaint ID, primary wallet address, chain, priority, status, risk score, and linked traced transactions." },
      { q: "Can investigators generate an investigation report?", a: "Yes, a PDF investigation report can be generated from the Reports & Requests view for a selected case." },
    ],
  },
  {
    category: "Freeze Workflow",
    items: [
      { q: "What is a Freeze Request?", a: "It's an internal, auditable request record created by an investigator recommending that a wallet's activity be frozen, along with its supporting rationale." },
      { q: "Does generating a PDF actually freeze a wallet?", a: "No. Generating a Freeze Request creates an auditable request and supporting document. Actual enforcement requires the relevant exchange, custodian, or authority integration." },
    ],
  },
  {
    category: "Security / Evidence",
    items: [
      { q: "Does CryptoTrace modify blockchain data?", a: "No. CryptoTrace only reads and analyzes blockchain transaction data; it does not write to or alter the blockchain." },
      { q: "Does CryptoTrace store private keys or move funds?", a: "No. CryptoTrace does not request, store, or use private keys, and has no capability to move or control cryptocurrency funds." },
    ],
  },
];

function useSmoothScroll() {
  return (id: string) => {
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
  };
}

function HomePage() {
  const navigate = useNavigate();
  const scrollTo = useSmoothScroll();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [openFaq, setOpenFaq] = useState<string | null>(null);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 12);
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const goToApp = () => navigate({ to: "/login" });

  const handleNavClick = (id: string) => {
    scrollTo(id);
    setMobileOpen(false);
  };

  return (
    <div style={{ background: BG, color: "#e6ecf1", minHeight: "100vh", fontFamily: "inherit" }}>
      {/* NAVBAR */}
      <header
        style={{
          position: "sticky",
          top: 0,
          zIndex: 100,
          background: scrolled ? "rgba(11,15,20,0.9)" : "rgba(11,15,20,0.6)",
          backdropFilter: "blur(10px)",
          borderBottom: `1px solid ${scrolled ? BORDER : "transparent"}`,
          transition: "all 0.25s ease",
        }}
      >
        <div
          style={{
            maxWidth: 1200,
            margin: "0 auto",
            padding: "14px 24px",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            gap: 16,
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <img src="/favicon.png" alt="CryptoTrace logo" style={{ width: 32, height: 32, objectFit: "contain" }} />
            <strong style={{ fontSize: 17 }}>CryptoTrace</strong>
          </div>

          <nav style={{ display: "flex", gap: 32 }} className="landing-nav-desktop">
            {NAV_LINKS.map((link) => (
              <button
                key={link.id}
                onClick={() => handleNavClick(link.id)}
                style={{
                  background: "none",
                  border: "none",
                  color: MUTED,
                  fontSize: 14,
                  cursor: "pointer",
                  padding: 0,
                }}
                onMouseEnter={(e) => (e.currentTarget.style.color = "#e6ecf1")}
                onMouseLeave={(e) => (e.currentTarget.style.color = MUTED)}
              >
                {link.label}
              </button>
            ))}
          </nav>

          <div style={{ display: "flex", alignItems: "center", gap: 12 }} className="landing-nav-desktop">
            <button
              onClick={() => navigate({ to: "/login" })}
              style={{ background: "none", border: "none", color: "#e6ecf1", fontSize: 14, cursor: "pointer" }}
            >
              Login
            </button>
            <button
              onClick={goToApp}
              style={{
                background: ACCENT,
                color: "#04201c",
                border: "none",
                borderRadius: 8,
                padding: "9px 18px",
                fontSize: 14,
                fontWeight: 600,
                cursor: "pointer",
              }}
            >
              Get Started
            </button>
          </div>

          <button
            aria-label="Toggle menu"
            onClick={() => setMobileOpen((v) => !v)}
            className="landing-nav-mobile-btn"
            style={{ background: "none", border: "none", color: "#e6ecf1", display: "none" }}
          >
            {mobileOpen ? <X size={22} /> : <Menu size={22} />}
          </button>
        </div>

        {mobileOpen && (
          <div
            className="landing-nav-mobile-panel"
            style={{
              borderTop: `1px solid ${BORDER}`,
              padding: "16px 24px",
              display: "flex",
              flexDirection: "column",
              gap: 14,
              background: BG,
            }}
          >
            {NAV_LINKS.map((link) => (
              <button
                key={link.id}
                onClick={() => handleNavClick(link.id)}
                style={{ background: "none", border: "none", color: "#e6ecf1", fontSize: 15, textAlign: "left", padding: 0 }}
              >
                {link.label}
              </button>
            ))}
            <button
              onClick={() => {
                setMobileOpen(false);
                navigate({ to: "/login" });
              }}
              style={{ background: "none", border: "none", color: "#e6ecf1", fontSize: 15, textAlign: "left", padding: 0 }}
            >
              Login
            </button>
            <button
              onClick={() => {
                setMobileOpen(false);
                goToApp();
              }}
              style={{
                background: ACCENT,
                color: "#04201c",
                border: "none",
                borderRadius: 8,
                padding: "10px 18px",
                fontSize: 14,
                fontWeight: 600,
                cursor: "pointer",
                marginTop: 4,
              }}
            >
              Get Started
            </button>
          </div>
        )}
      </header>

      {/* HERO */}
      <section style={{ maxWidth: 900, margin: "0 auto", padding: "90px 24px 90px", textAlign: "center" }}>
        <div
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: 8,
            border: `1px solid ${BORDER}`,
            borderRadius: 999,
            padding: "6px 14px",
            fontSize: 12,
            color: ACCENT,
            marginBottom: 24,
          }}
        >
          <ShieldCheck size={13} /> Digital Asset Investigation Platform
        </div>
        <h1 style={{ fontSize: "clamp(32px, 5vw, 52px)", lineHeight: 1.15, margin: 0, fontWeight: 700 }}>
          Trace Crypto. Detect Fraud. <span style={{ color: ACCENT }}>Protect Assets.</span>
        </h1>
        <p style={{ color: MUTED, fontSize: 16, marginTop: 20, lineHeight: 1.6, maxWidth: 680, marginLeft: "auto", marginRight: "auto" }}>
          CryptoTrace helps investigators trace suspicious cryptocurrency transactions, analyze wallet behavior,
          assess risk, and generate actionable investigation evidence — grounded in real blockchain data.
        </p>
        <div style={{ display: "flex", gap: 14, justifyContent: "center", marginTop: 32, flexWrap: "wrap" }}>
          <button
            onClick={goToApp}
            style={{
              background: ACCENT,
              color: "#04201c",
              border: "none",
              borderRadius: 8,
              padding: "13px 26px",
              fontSize: 15,
              fontWeight: 600,
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              gap: 8,
            }}
          >
            Start Investigation <ArrowRight size={16} />
          </button>
          <button
            onClick={() => handleNavClick("how-it-works")}
            style={{
              background: "transparent",
              color: "#e6ecf1",
              border: `1px solid ${BORDER}`,
              borderRadius: 8,
              padding: "13px 26px",
              fontSize: 15,
              cursor: "pointer",
            }}
          >
            Explore How It Works
          </button>
        </div>
        {/* graph/node illustration removed */}
      </section>

      {/* FEATURES */}
      <section id="features" style={{ maxWidth: 1200, margin: "0 auto", padding: "60px 24px" }}>
        <SectionHeader eyebrow="CAPABILITIES" title="What CryptoTrace does" />
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
            gap: 20,
            marginTop: 40,
          }}
        >
          {FEATURES.map((f) => {
            const Icon = f.icon;
            return (
              <div
                key={f.title}
                style={{
                  border: `1px solid ${BORDER}`,
                  borderRadius: 14,
                  background: PANEL_BG,
                  padding: 24,
                  transition: "transform 0.2s ease, border-color 0.2s ease",
                  cursor: "default",
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.transform = "translateY(-3px)";
                  e.currentTarget.style.borderColor = ACCENT;
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.transform = "translateY(0)";
                  e.currentTarget.style.borderColor = BORDER;
                }}
              >
                <div
                  style={{
                    width: 40,
                    height: 40,
                    borderRadius: 10,
                    background: "rgba(34,230,200,0.1)",
                    display: "grid",
                    placeItems: "center",
                    marginBottom: 16,
                  }}
                >
                  <Icon size={19} color={ACCENT} />
                </div>
                <h3 style={{ fontSize: 16, margin: "0 0 8px" }}>{f.title}</h3>
                <p style={{ fontSize: 13.5, color: MUTED, lineHeight: 1.6, margin: 0 }}>{f.desc}</p>
              </div>
            );
          })}
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section id="how-it-works" style={{ maxWidth: 1200, margin: "0 auto", padding: "60px 24px" }}>
        <SectionHeader eyebrow="WORKFLOW" title="How It Works" />
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
            gap: 20,
            marginTop: 40,
          }}
        >
          {STEPS.map((s) => (
            <div
              key={s.n}
              style={{
                border: `1px solid ${BORDER}`,
                borderRadius: 14,
                background: PANEL_BG,
                padding: 24,
              }}
            >
              <span style={{ fontSize: 28, fontWeight: 700, color: ACCENT }}>{s.n}</span>
              <h3 style={{ fontSize: 15, margin: "12px 0 8px" }}>{s.title}</h3>
              <p style={{ fontSize: 13.5, color: MUTED, lineHeight: 1.6, margin: 0 }}>{s.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* TECHNOLOGY -> HOW IT'S BUILT */}
      <section id="technology" style={{ maxWidth: 1200, margin: "0 auto", padding: "60px 24px" }}>
        <SectionHeader eyebrow="ARCHITECTURE" title="How It's Built" />
        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: 20,
            marginTop: 40,
            justifyContent: "center",
          }}
        >
          {BUILD_BLOCKS.map((b, i) => {
            const Icon = b.icon;
            return (
              <div
                key={b.title}
                style={{
                  flex: "1 1 260px",
                  maxWidth: 320,
                  border: `1px solid ${BORDER}`,
                  borderRadius: 14,
                  background: PANEL_BG,
                  padding: 24,
                  display: "flex",
                  flexDirection: "column",
                  gap: 12,
                  cursor: "default",
                  transition: "transform 0.35s ease, border-color 0.35s ease, box-shadow 0.35s ease",
                  animation: `buildFadeIn 0.5s ease ${i * 0.08}s both`,
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.transform = "translateY(-6px) scale(1.02)";
                  e.currentTarget.style.borderColor = ACCENT;
                  e.currentTarget.style.boxShadow = "0 12px 30px rgba(34,230,200,0.12)";
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.transform = "translateY(0) scale(1)";
                  e.currentTarget.style.borderColor = BORDER;
                  e.currentTarget.style.boxShadow = "none";
                }}
              >
                <div
                  style={{
                    width: 42,
                    height: 42,
                    borderRadius: 10,
                    background: "rgba(34,230,200,0.1)",
                    display: "grid",
                    placeItems: "center",
                    transition: "background 0.35s ease, transform 0.35s ease",
                  }}
                >
                  <Icon size={20} color={ACCENT} />
                </div>
                <h3 style={{ fontSize: 15.5, margin: 0 }}>{b.title}</h3>
                <p style={{ fontSize: 13.5, color: MUTED, lineHeight: 1.6, margin: 0 }}>{b.desc}</p>
              </div>
            );
          })}
        </div>
      </section>

      {/* FAQ (trimmed) */}
      <section id="faq" style={{ maxWidth: 860, margin: "0 auto", padding: "60px 24px" }}>
        <SectionHeader eyebrow="FAQ" title="Frequently Asked Questions" />
        <div style={{ marginTop: 32 }}>
          {FAQS.map((group) => (
            <div key={group.category} style={{ marginBottom: 28 }}>
              <h4 style={{ fontSize: 13, color: ACCENT, letterSpacing: 0.5, marginBottom: 12 }}>
                {group.category.toUpperCase()}
              </h4>
              <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                {group.items.map((item) => {
                  const key = `${group.category}-${item.q}`;
                  const isOpen = openFaq === key;
                  return (
                    <div
                      key={key}
                      style={{
                        border: `1px solid ${BORDER}`,
                        borderRadius: 10,
                        background: PANEL_BG,
                        overflow: "hidden",
                      }}
                    >
                      <button
                        onClick={() => setOpenFaq(isOpen ? null : key)}
                        style={{
                          width: "100%",
                          background: "none",
                          border: "none",
                          color: "#e6ecf1",
                          padding: "14px 16px",
                          display: "flex",
                          justifyContent: "space-between",
                          alignItems: "center",
                          fontSize: 14,
                          cursor: "pointer",
                          textAlign: "left",
                        }}
                      >
                        {item.q}
                        <ChevronDown
                          size={16}
                          style={{
                            transform: isOpen ? "rotate(180deg)" : "rotate(0deg)",
                            transition: "transform 0.2s ease",
                            flexShrink: 0,
                            marginLeft: 12,
                          }}
                        />
                      </button>
                      <div
                        style={{
                          maxHeight: isOpen ? 300 : 0,
                          transition: "max-height 0.25s ease",
                          overflow: "hidden",
                        }}
                      >
                        <p style={{ padding: "0 16px 16px", margin: 0, fontSize: 13.5, color: MUTED, lineHeight: 1.6 }}>
                          {item.a}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* FINAL CTA */}
      <section style={{ maxWidth: 900, margin: "0 auto", padding: "70px 24px", textAlign: "center" }}>
        <div
          style={{
            border: `1px solid ${BORDER}`,
            borderRadius: 20,
            background: "linear-gradient(135deg, rgba(34,230,200,0.08), rgba(255,255,255,0.02))",
            padding: "48px 32px",
          }}
        >
          <h2 style={{ fontSize: "clamp(22px, 4vw, 32px)", margin: 0, fontWeight: 700 }}>
            Turn Blockchain Evidence Into Actionable Investigations.
          </h2>
          <p style={{ color: MUTED, fontSize: 15, marginTop: 16, maxWidth: 560, marginLeft: "auto", marginRight: "auto" }}>
            Trace suspicious wallets, understand transaction flows, assess risk, and build evidence-backed
            investigation workflows.
          </p>
          <button
            onClick={goToApp}
            style={{
              marginTop: 28,
              background: ACCENT,
              color: "#04201c",
              border: "none",
              borderRadius: 8,
              padding: "13px 28px",
              fontSize: 15,
              fontWeight: 600,
              cursor: "pointer",
            }}
          >
            Start Investigation
          </button>
        </div>
      </section>

      {/* FOOTER */}
      <footer style={{ borderTop: `1px solid ${BORDER}`, padding: "36px 24px" }}>
        <div
          style={{
            maxWidth: 1200,
            margin: "0 auto",
            display: "flex",
            flexWrap: "wrap",
            justifyContent: "space-between",
            gap: 24,
          }}
        >
          <div>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <img src="/favicon.png" alt="CryptoTrace logo" style={{ width: 24, height: 24, objectFit: "contain" }} />
              <strong style={{ fontSize: 15 }}>CryptoTrace</strong>
            </div>
            <p style={{ color: MUTED, fontSize: 12.5, marginTop: 8, maxWidth: 280 }}>
              Blockchain Intelligence for Digital Fraud Investigation
            </p>
          </div>
          <div style={{ display: "flex", gap: 24, flexWrap: "wrap" }}>
            {NAV_LINKS.map((link) => (
              <button
                key={link.id}
                onClick={() => handleNavClick(link.id)}
                style={{ background: "none", border: "none", color: MUTED, fontSize: 13, cursor: "pointer", padding: 0 }}
              >
                {link.label}
              </button>
            ))}
            <button
              onClick={() => navigate({ to: "/login" })}
              style={{ background: "none", border: "none", color: MUTED, fontSize: 13, cursor: "pointer", padding: 0 }}
            >
              Login
            </button>
          </div>
        </div>
      </footer>

      <style>{`
        @media (max-width: 860px) {
          .landing-nav-desktop { display: none !important; }
          .landing-nav-mobile-btn { display: block !important; }
        }
        @keyframes buildFadeIn {
          from { opacity: 0; transform: translateY(14px); }
          to { opacity: 1; transform: translateY(0); }
        }
      `}</style>
    </div>
  );
}

function SectionHeader({ eyebrow, title }: { eyebrow: string; title: string }) {
  return (
    <div style={{ textAlign: "center" }}>
      <span style={{ fontSize: 12, letterSpacing: 1.5, color: ACCENT }}>{eyebrow}</span>
      <h2 style={{ fontSize: "clamp(24px, 4vw, 34px)", margin: "8px 0 0", fontWeight: 700 }}>{title}</h2>
    </div>
  );
}